language: ruby

cache: bundler

branches:
  only:
  - develop

script:
- JEKYLL_ENV=production bundle exec jekyll build --destination site

deploy:
  provider: pages
  local-dir: ./site
  github-token: $GITHUB_TOKEN
  target-branch: master
  skip-cleanup: true
  keep-history: true
  on:
    branch: develop